version: "3.9"

services:
  oracle-db:
    image: wnameless/oracle-xe-11g
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "8080:8080"
    environment:
      - ORACLE_PWD=12345
    volumes:
      - oracle-data:/u01/app/oracle
    restart: unless-stopped

  backend-api:
    build:
      context: ./Ecommerce_Back_End
      dockerfile: Dockerfile
    container_name: backend-app
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=User Id=system;Password=12345;Data Source=oracle-db:1521/xe
    depends_on:
      - oracle-db
    restart: unless-stopped

  frontend-app:
    build:
      context: ./project-sarona
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "4200:80"
    environment:
      - API_URL=http://backend-api:80
    depends_on:
      - backend-api
    restart: unless-stopped

volumes:
  oracle-data:
