// <auto-generated />
using System;
using Ecommerce_Back_End;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Ecommerce_Back_End.Migrations
{
    [DbContext(typeof(EcommerceDbContext))]
    [Migration("20250705081848_AddProductSpecification")]
    partial class AddProductSpecification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce_Back_End.Model.Data.Cart", b =>
                {
                    b.Property<int>("CARTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CARTID"));

                    b.Property<DateTime>("CREATEDATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("MODIFIEDDATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("PROID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("QTY")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("USERID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("CARTID");

                    b.ToTable("CART_TBL");
                });

            modelBuilder.Entity("Ecommerce_Back_End.Model.Data.Category", b =>
                {
                    b.Property<int>("CATEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CATEID"));

                    b.Property<string>("CATEDESC")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CATENAME")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("CREATEDATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DELETEDDATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("MODIFIEDDATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("STATUS")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("CATEID");

                    b.ToTable("CATEGORY_TBL");
                });

            modelBuilder.Entity("Ecommerce_Back_End.Model.Data.Order", b =>
                {
                    b.Property<int>("ORDERID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ORDERID"));

                    b.Property<string>("ADDRESSLINE")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CITY")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("COUNTRY")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("CREATEDATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("MODIFIEDDATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ORDERNUMBER")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("PAYMENTID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<float>("PRICE")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<int>("PROID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("QTY")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<float>("TOTAL")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<int>("USERID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ZIPCODE")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ORDERID");

                    b.ToTable("ORDER_TBL");
                });

            modelBuilder.Entity("Ecommerce_Back_End.Model.Data.PaymentDetail", b =>
                {
                    b.Property<int>("PAYID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PAYID"));

                    b.Property<float>("AMOUNT")
                        .HasColumnType("BINARY_FLOAT");

                    b.Property<DateTime>("CREATEDATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("MODIFIEDDATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("PROVIDER")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("STATUS")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("PAYID");

                    b.ToTable("PAYMENTDETAIL_TBL");
                });

            modelBuilder.Entity("Ecommerce_Back_End.Model.Data.Product", b =>
                {
                    b.Property<int>("PROID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PROID"));

                    b.Property<int>("CATEID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("CREATEDATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DELETEDDATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("IMAGE")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("MODIFIEDDATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<decimal>("PRICE")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("PRODESC")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PRONAME")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("PROSPECID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("QTY")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("STATUS")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("SUBCATEID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("PROID");

                    b.ToTable("PRODUCT_TBL");
                });

            modelBuilder.Entity("Ecommerce_Back_End.Model.Data.ProductSpecification", b =>
                {
                    b.Property<int>("PROSPECID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PROSPECID"));

                    b.Property<string>("AUDIO")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("BACKPANELCONNECTOR")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("BARCODE")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("BATTERY")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("BIOS")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("BRIGHTNESS")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CABLELENGTH")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CHIPSET")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CONNECTIVITY")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DEPTH")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DISPLAY")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DPI")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EXPANSIONSLOT")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("HEIGHT")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("INTERNALIO")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("IOCONTROLLER")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("LAN")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MEMORY")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ONBOARDGRAPHICS")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("OS")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PANEL_TYPE")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PROCESSOR")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("REFRESH_RATE")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RESOLUTION")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("STORAGE")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("STORAGEINTERFACE")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SYSREQUIREMENT")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UNIQUEFEATURE")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("USB")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("VIDEOCARD")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("WARRANTY")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("WEIGHT")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("WIDTH")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("WIFI")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("WIRELESSCONECT")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("PROSPECID");

                    b.ToTable("PRODUCTSPECIFICATION_TBL");
                });

            modelBuilder.Entity("Ecommerce_Back_End.Model.Data.SubCategory", b =>
                {
                    b.Property<int>("SUBCATEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SUBCATEID"));

                    b.Property<int>("CATEID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SUBCATEGORY")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("SUBCATEID");

                    b.ToTable("SUBCATEGORY_TBL");
                });

            modelBuilder.Entity("Ecommerce_Back_End.Model.Data.User", b =>
                {
                    b.Property<int>("USERID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("USERID"));

                    b.Property<DateTime?>("CREATEDATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("GENDER")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("MODIFIEDDATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PHONE")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("USERNAME")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("USERTYPE")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("USERID");

                    b.HasIndex("USERNAME")
                        .IsUnique();

                    b.ToTable("USER_TBL");
                });

            modelBuilder.Entity("Ecommerce_Back_End.Model.Data.Wishlist", b =>
                {
                    b.Property<int>("WISHLISTID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WISHLISTID"));

                    b.Property<DateTime>("CREATEDATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("MODIFIEDDATE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("PROID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("USERID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("WISHLISTID");

                    b.ToTable("WISHLIST_TBL");
                });
#pragma warning restore 612, 618
        }
    }
}
